version: 1.1.0.{build}
skip_tags: true
image:
  - Visual Studio 2017
init:
- ps: 
environment:
  PowershellGalleryKey:
    secure: eYjRH/vLjuc425MocEniahdNMctg+z44QhT1l4rn8GOcpcixPW/wIwskO5xrFg2T
  GitHubKey:
    secure: T4FEQ69B/omx+5e6RuhQaG58Q7QzQRJJ9tweJRhLaaGfi0oiRlRUUYwT6JJUeavK
install:
- ps: |
    import-module powershellget
    Install-module PowerShellGet -force -AllowClobber -SkipPublisherCheck
    Remove-Module PowerShellGet -Force
    Import-Module PowerShellGet -Force

    Get-PackageProvider -Name NuGet -ForceBootstrap

    install-module pester -force -AllowClobber -SkipPublisherCheck
    install-module psake -force -AllowClobber -SkipPublisherCheck
build_script:
- ps: invoke-psake -TaskList Restore,SetVersion
before_deploy:
- ps: |
      if($env:APPVEYOR_REPO_BRANCH -eq "master") {
        ipmo powershellget
        
        publish-module -Path .\QrCodes -NuGetApiKey "$env:PowerShellGalleryKey" -Tag QRCode,ZXing
      }
deploy:
- provider: GitHub
  tag: $(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: au7U3lCQxP2uBfxLTMBjQP4Wbaj6m6bIePUDpEfGIzfHELRVoXjt0y+gLC6KsSNI
  draft: true
  on:
    APPVEYOR_REPO_BRANCH: master