version: 1.0.0.{build}
skip_tags: true
image:
  - Visual Studio 2017
init:
- ps: 
environment:
  PowershellGalleryKey:
    secure: Klw85ScA90qbL+f6QPgqTJ1yEM84GdsjSr132EGKsLPUJkBZXzE8/9lsOHcMDPOS
  GitHubKey:
    secure: T4FEQ69B/omx+5e6RuhQaG58Q7QzQRJJ9tweJRhLaaGfi0oiRlRUUYwT6JJUeavK
install:
- ps: |
    import-module powershellget
    Install-module PowerShellGet -force -AllowClobber -SkipPublisherCheck
    Remove-Module PowerShellGet -Force
    Import-Module PowerShellGet -Force

    Get-PackageProvider -Name NuGet -ForceBootstrap

    install-module pester -force -AllowClobber -SkipPublisherCheck
    install-module psake -force -AllowClobber -SkipPublisherCheck
build_script:
- ps: invoke-psake -TaskList Restore,SetVersion
deploy_script:
- ps: |
      if($env:APPVEYOR_REPO_BRANCH -eq "master") {
        ipmo psake
        ipmo powershellget
        
        publish-module -Path .\QrCodes -NuGetApiKey '$env:PowerShellGalleryKey' -Tag QRCode,ZXing -ProjectUri https://github.com/gpduck/QrCodes
        
        git config --global credential.helper store
        Add-Content "$env:USERPROFILE\.git-credentials" "https://${env:GitHubKey}:x-oauth-basic@github.com`n"
        
        git tag $env:APPVEYOR_BUILD_VERSION
        git push origin -q $env:APPVEYOR_BUILD_VERSION
      } 
